# Projektin Nimi (TBD)

Tony Karlin, Onni Kivinen, Joni Heikkilä, Jarkko Kärki

## 1.0 Business understanding

## 2.0 Data understanding

In [72]:
import geopandas as gpd
import pandas as pd

geodata_filepath = "datasets/piirialuejako-1995-2019.gpkg"
areas = gpd.read_file(geodata_filepath, layer="osa_alue_2019")

accidents_filepath = "datasets/liikenneonnettomuudet.csv"
df = pd.read_csv(accidents_filepath, sep=";", decimal=",")

In [73]:
accidents = gpd.GeoDataFrame(
    df,
    geometry=gpd.points_from_xy(df["ita_etrs"], df["pohj_etrs"]),
    crs="EPSG:3879"
)
areas = areas.to_crs(accidents.crs)

accidents = gpd.sjoin(
    accidents,
    areas[["Nimi", "geometry"]],
    how="left",
    predicate="within"
)

accidents = accidents.rename(columns={"Nimi": "Osa-alue"})
accidents = accidents.drop(columns=["geometry", "index_right"])

In [74]:
# Sarakkeiden uudellennimeäminen
col_rename = {"LAJI": "O_Tyyppi", "pohj_etrs": "Pohj_coords", "ita_etrs": "Itä_coords","VAKAV_A": "Vakavuus", "VV": "Vuosi"}
accidents = accidents.rename(columns=col_rename)

# Sarakkeiden uudelleenjärjestys
accidents = accidents.iloc[:, [1, 2, 5, 0, 4, 3]]
accidents

      Pohj_coords   Itä_coords      Osa-alue O_Tyyppi  Vuosi  Vakavuus
0      6675786.73  25501661.91  Länsi-Hertto       JK   2022         1
1      6674533.32  25502790.94      Yliskylä       JK   2022         2
2      6679536.47  25506837.81    Mellunmäki       JK   2022         2
3      6675297.68  25498807.13    Kalasatama       JK   2022         2
4      6674924.21  25495525.13    Taka-Töölö       JK   2022         2
...           ...          ...           ...      ...    ...       ...
53795  6674696.29  25497044.46        Linjat       PP   2024         2
53796  6675329.91  25497183.32       Vallila       PP   2024         1
53797  6675746.02  25494119.16  Pikku Huopal       PP   2024         1
53798  6678387.52  25494869.15      Kivihaka       PP   2024         1
53799  6684306.71  25502593.86      Puistola       PP   2024         2

[53800 rows x 6 columns]

In [75]:
print(accidents.dtypes)

Pohj_coords      str
Itä_coords       str
Osa-alue         str
O_Tyyppi         str
Vuosi          int64
Vakavuus       int64
dtype: object

In [76]:
# Sarakkeiden muuttaminen tyypistä str -> Categorical
cols_to_categorical = ["Osa-alue", "O_Tyyppi"]
accidents[cols_to_categorical] = accidents[cols_to_categorical].astype("category")

cols_to_float = ["Pohj_coords", "Itä_coords"]
accidents[cols_to_float] = accidents[cols_to_float].astype(float)

In [77]:
print(accidents.dtypes)

Pohj_coords     float64
Itä_coords      float64
Osa-alue       category
O_Tyyppi       category
Vuosi             int64
Vakavuus          int64
dtype: object

In [78]:
accidents.describe(include='all')

,Pohj_coords,Itä_coords,Osa-alue,O_Tyyppi,Vuosi,Vakavuus
count,5.379700e+04,5.379700e+04,53786,53800,53800.000000,53800.000000
unique,NaN,NaN,140,4,NaN,NaN
top,NaN,NaN,Kamppi,MA,NaN,NaN
freq,NaN,NaN,3230,44837,NaN,NaN
mean,6.676639e+06,2.549795e+07,NaN,NaN,2009.893625,1.212974
std,3.502269e+03,3.695722e+03,NaN,NaN,6.409066,0.418883
min,6.670495e+06,2.549076e+07,NaN,NaN,2000.000000,1.000000
25%,6.673407e+06,2.549564e+07,NaN,NaN,2004.000000,1.000000
50%,6.676020e+06,2.549701e+07,NaN,NaN,2010.000000,1.000000
75%,6.679532e+06,2.550009e+07,NaN,NaN,2015.000000,1.000000
max,6.686071e+06,2.551361e+07,NaN,NaN,2024.000000,3.000000

## 3.0 Data preparation

## 4.0 Modeling

## 5.0 Evaluation

## 6.0 Deployment